### PR TITLE
Resolved ambiguity in simd_word test by explicitly casting size_t to uint64_t for << operator usage.

### PR DESCRIPTION
**Pull request by sengthai**

### CODE REVIEW

**Comment by Strilanc** [comment]
What is the ambiguity that's being resolved?

**Comment by sengthai** [comment]
> What is the ambiguity that's being resolved?

The ambiguity is when using the `<<` operator between `simd_word<W>` and `size_t` type. The compiler may not determine which overloaded `<<` operator to use. By casting one operand to `uint64_t`, we specify which operator to use, eliminating the ambiguity.

**Comment by AntonMenshov** [comment]
I confirm that without this fix, the compilation on AppleClang 15.0.0 is problematic (essentially, boiling down to the compiler erroring out on trying to find the right match for the `<<` operator in the aforementioned unit test).

**Comment by sengthai** [comment]
@AntonMenshov  Oh I see. Thank you for confirmation.

**Comment by Strilanc** [comment]
Sorry for the delay on merging this. I see you closed it; I moved the changes over to https://github.com/quantumlib/Stim/pull/758

**Pull request closed without merging**
