### PR TITLE
Fix order of operations in Tableau.__call__.__doc__

### PR DESCRIPTION
**Pull request by amirebrahimi**
This is minor, but I figure it might save someone else some time.

### CODE REVIEW

**Comment by amirebrahimi** [comment]
I just signed the CLA, so not sure if it will require CI to rerun.

**Comment by Strilanc** [comment]
Everyone always edits the generated docs instead of the source.

If the multiplication is in circuit order, then that's the wrong way around. I should fix that and then also separately describe it as "before/after" so it's clearer.

**Comment by amirebrahimi** [comment]
This seems to be consistent with what is specified [here](https://github.com/quantumlib/Stim/blob/main/src/stim/stabilizers/tableau.h#L133).

**Comment by Strilanc** [comment]
Fixes https://github.com/quantumlib/Stim/issues/819

**Comment by Strilanc** [comment]
Moved to https://github.com/quantumlib/Stim/pull/822 so I could edit it to get it merged. Thanks for the fix!

**Pull request closed without merging**
