### PR TITLE
Exposing FrameSimulator to python

### PR DESCRIPTION
**Pull request by danielbarter**
Exposing FrameSimulator to python

### CODE REVIEW

**Review by Strilanc — CHANGES_REQUESTED** [review]
I don't think this change is nearly sufficient. For example, I suspect any fuzz test is now copying a the shared RNG each time and so getting exactly the same samples.

Basically every single invocation of the constructor needs to be revisited.

I would actually recommend first changing this to std::unique_ptr, making that works (because it will make all existing calls fail), THEN inlining it to direct ownership.

**Comment by danielbarter** [comment]
That is a good idea. I was planning on phasing out `SHARED_TEST_RNG` and just calling `externally_seeded_rng` directly.

**Comment by Strilanc** [comment]
> I was planning on phasing out SHARED_TEST_RNG and just calling externally_seeded_rng directly. Should get to the same place right?

Yes, that's what you should do.

**Comment by danielbarter** [comment]
I haven't forgotten about this! Hopefully will have some time to work on it next week

**Pull request closed without merging**
