### PR TITLE
[draft] a little doc bug in r8 parser

### PR DESCRIPTION
**Pull request by balopat**
I think we only want to append the 0s to the shot when it's not the next byte is not special.

### CODE REVIEW

**Comment by balopat** [comment]
haha, the cla flag, I'll see what I can do.

**Comment by balopat** [comment]
actually I'm not sure about this solution either, need to actually test it. Marking it as draft.

**Comment by Strilanc** [comment]
I'm quite confident the original version is correct and this version is wrong. When you see `0xFF` you're supposed to append 255 zeroes. Otherwise the special byte would be a no-op and you'd have no way of encoding runs of 0s longer than 254.

These snippets are tested, by the way, so I'm expecting CI to fail.

**Comment by Strilanc** [comment]
(Actually the failure will likely be that the docs need to be regenerated because you edited the output instead of the input.)

**Comment by balopat** [comment]
Ah, very nice, I misunderstood on the first read, but you actually specify it clearly in the doc `it indicates to include 255 False bits but not follow them by a True bit. `. Closing!

**Pull request closed without merging**
